/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Hackathon DH API
 * WIP
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  CreateSessionDto,
  Session,
  SesssionVideoDataDto,
  UpdateSessionDto,
  UploadPoseDataDto,
} from '.././model';

import { customInstance } from '.././mutator/custom-instance';
import type { ErrorType } from '.././mutator/custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Create a new session for a user
 */
export const sessionControllerCreate = (
  createSessionDto: CreateSessionDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<Session>(
    {
      url: `/sessions`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createSessionDto,
      signal,
    },
    options,
  );
};

export const getSessionControllerCreateMutationOptions = <
  TError = ErrorType<Session>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sessionControllerCreate>>,
    TError,
    { data: CreateSessionDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sessionControllerCreate>>,
  TError,
  { data: CreateSessionDto },
  TContext
> => {
  const mutationKey = ['sessionControllerCreate'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sessionControllerCreate>>,
    { data: CreateSessionDto }
  > = (props) => {
    const { data } = props ?? {};

    return sessionControllerCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SessionControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof sessionControllerCreate>>
>;
export type SessionControllerCreateMutationBody = CreateSessionDto;
export type SessionControllerCreateMutationError = ErrorType<Session>;

/**
 * @summary Create a new session for a user
 */
export const useSessionControllerCreate = <
  TError = ErrorType<Session>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof sessionControllerCreate>>,
      TError,
      { data: CreateSessionDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof sessionControllerCreate>>,
  TError,
  { data: CreateSessionDto },
  TContext
> => {
  const mutationOptions = getSessionControllerCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Returns all user sesssion
 */
export const sessionControllerFindAll = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<Session[]>(
    { url: `/sessions`, method: 'GET', signal },
    options,
  );
};

export const getSessionControllerFindAllQueryKey = () => {
  return [`/sessions`] as const;
};

export const getSessionControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof sessionControllerFindAll>>,
  TError = ErrorType<Session[]>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof sessionControllerFindAll>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSessionControllerFindAllQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof sessionControllerFindAll>>
  > = ({ signal }) => sessionControllerFindAll(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof sessionControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SessionControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof sessionControllerFindAll>>
>;
export type SessionControllerFindAllQueryError = ErrorType<Session[]>;

export function useSessionControllerFindAll<
  TData = Awaited<ReturnType<typeof sessionControllerFindAll>>,
  TError = ErrorType<Session[]>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof sessionControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sessionControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof sessionControllerFindAll>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSessionControllerFindAll<
  TData = Awaited<ReturnType<typeof sessionControllerFindAll>>,
  TError = ErrorType<Session[]>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof sessionControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sessionControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof sessionControllerFindAll>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSessionControllerFindAll<
  TData = Awaited<ReturnType<typeof sessionControllerFindAll>>,
  TError = ErrorType<Session[]>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof sessionControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Returns all user sesssion
 */

export function useSessionControllerFindAll<
  TData = Awaited<ReturnType<typeof sessionControllerFindAll>>,
  TError = ErrorType<Session[]>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof sessionControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSessionControllerFindAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update a session by id
 */
export const sessionControllerUpdate = (
  id: string,
  updateSessionDto: UpdateSessionDto,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    {
      url: `/sessions/${id}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateSessionDto,
    },
    options,
  );
};

export const getSessionControllerUpdateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sessionControllerUpdate>>,
    TError,
    { id: string; data: UpdateSessionDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sessionControllerUpdate>>,
  TError,
  { id: string; data: UpdateSessionDto },
  TContext
> => {
  const mutationKey = ['sessionControllerUpdate'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sessionControllerUpdate>>,
    { id: string; data: UpdateSessionDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return sessionControllerUpdate(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SessionControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof sessionControllerUpdate>>
>;
export type SessionControllerUpdateMutationBody = UpdateSessionDto;
export type SessionControllerUpdateMutationError = ErrorType<void>;

/**
 * @summary Update a session by id
 */
export const useSessionControllerUpdate = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof sessionControllerUpdate>>,
      TError,
      { id: string; data: UpdateSessionDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof sessionControllerUpdate>>,
  TError,
  { id: string; data: UpdateSessionDto },
  TContext
> => {
  const mutationOptions = getSessionControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Delete a session by id
 */
export const sessionControllerDelete = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    { url: `/sessions/${id}`, method: 'DELETE' },
    options,
  );
};

export const getSessionControllerDeleteMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sessionControllerDelete>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sessionControllerDelete>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['sessionControllerDelete'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sessionControllerDelete>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return sessionControllerDelete(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SessionControllerDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof sessionControllerDelete>>
>;

export type SessionControllerDeleteMutationError = ErrorType<void>;

/**
 * @summary Delete a session by id
 */
export const useSessionControllerDelete = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof sessionControllerDelete>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof sessionControllerDelete>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getSessionControllerDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get a session by id
 */
export const sessionControllerFindOne = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<Session>(
    { url: `/sessions/${id}`, method: 'GET', signal },
    options,
  );
};

export const getSessionControllerFindOneQueryKey = (id: string) => {
  return [`/sessions/${id}`] as const;
};

export const getSessionControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof sessionControllerFindOne>>,
  TError = ErrorType<Session>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof sessionControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSessionControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof sessionControllerFindOne>>
  > = ({ signal }) => sessionControllerFindOne(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof sessionControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SessionControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof sessionControllerFindOne>>
>;
export type SessionControllerFindOneQueryError = ErrorType<Session>;

export function useSessionControllerFindOne<
  TData = Awaited<ReturnType<typeof sessionControllerFindOne>>,
  TError = ErrorType<Session>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof sessionControllerFindOne>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sessionControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof sessionControllerFindOne>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSessionControllerFindOne<
  TData = Awaited<ReturnType<typeof sessionControllerFindOne>>,
  TError = ErrorType<Session>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof sessionControllerFindOne>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sessionControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof sessionControllerFindOne>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSessionControllerFindOne<
  TData = Awaited<ReturnType<typeof sessionControllerFindOne>>,
  TError = ErrorType<Session>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof sessionControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a session by id
 */

export function useSessionControllerFindOne<
  TData = Awaited<ReturnType<typeof sessionControllerFindOne>>,
  TError = ErrorType<Session>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof sessionControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSessionControllerFindOneQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Upload a WebM video file with array data
 */
export const sessionControllerUploadVideo = (
  id: string,
  sesssionVideoDataDto: SesssionVideoDataDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  const formData = new FormData();
  formData.append('video', sesssionVideoDataDto.video);

  return customInstance<void>(
    {
      url: `/sessions/${id}/upload/video`,
      method: 'POST',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
      signal,
    },
    options,
  );
};

export const getSessionControllerUploadVideoMutationOptions = <
  TError = ErrorType<void | string>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sessionControllerUploadVideo>>,
    TError,
    { id: string; data: SesssionVideoDataDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sessionControllerUploadVideo>>,
  TError,
  { id: string; data: SesssionVideoDataDto },
  TContext
> => {
  const mutationKey = ['sessionControllerUploadVideo'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sessionControllerUploadVideo>>,
    { id: string; data: SesssionVideoDataDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return sessionControllerUploadVideo(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SessionControllerUploadVideoMutationResult = NonNullable<
  Awaited<ReturnType<typeof sessionControllerUploadVideo>>
>;
export type SessionControllerUploadVideoMutationBody = SesssionVideoDataDto;
export type SessionControllerUploadVideoMutationError = ErrorType<
  void | string
>;

/**
 * @summary Upload a WebM video file with array data
 */
export const useSessionControllerUploadVideo = <
  TError = ErrorType<void | string>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof sessionControllerUploadVideo>>,
      TError,
      { id: string; data: SesssionVideoDataDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof sessionControllerUploadVideo>>,
  TError,
  { id: string; data: SesssionVideoDataDto },
  TContext
> => {
  const mutationOptions =
    getSessionControllerUploadVideoMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Upload data at the end of a session
 */
export const sessionControllerUploadData = (
  id: string,
  uploadPoseDataDto: UploadPoseDataDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    {
      url: `/sessions/${id}/upload`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: uploadPoseDataDto,
      signal,
    },
    options,
  );
};

export const getSessionControllerUploadDataMutationOptions = <
  TError = ErrorType<Session>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sessionControllerUploadData>>,
    TError,
    { id: string; data: UploadPoseDataDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sessionControllerUploadData>>,
  TError,
  { id: string; data: UploadPoseDataDto },
  TContext
> => {
  const mutationKey = ['sessionControllerUploadData'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sessionControllerUploadData>>,
    { id: string; data: UploadPoseDataDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return sessionControllerUploadData(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SessionControllerUploadDataMutationResult = NonNullable<
  Awaited<ReturnType<typeof sessionControllerUploadData>>
>;
export type SessionControllerUploadDataMutationBody = UploadPoseDataDto;
export type SessionControllerUploadDataMutationError = ErrorType<Session>;

/**
 * @summary Upload data at the end of a session
 */
export const useSessionControllerUploadData = <
  TError = ErrorType<Session>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof sessionControllerUploadData>>,
      TError,
      { id: string; data: UploadPoseDataDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof sessionControllerUploadData>>,
  TError,
  { id: string; data: UploadPoseDataDto },
  TContext
> => {
  const mutationOptions =
    getSessionControllerUploadDataMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const sessionControllerGetSessionVideo = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { url: `/sessions/${id}/video`, method: 'GET', signal },
    options,
  );
};

export const getSessionControllerGetSessionVideoQueryKey = (id: string) => {
  return [`/sessions/${id}/video`] as const;
};

export const getSessionControllerGetSessionVideoQueryOptions = <
  TData = Awaited<ReturnType<typeof sessionControllerGetSessionVideo>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof sessionControllerGetSessionVideo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSessionControllerGetSessionVideoQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof sessionControllerGetSessionVideo>>
  > = ({ signal }) =>
    sessionControllerGetSessionVideo(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof sessionControllerGetSessionVideo>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SessionControllerGetSessionVideoQueryResult = NonNullable<
  Awaited<ReturnType<typeof sessionControllerGetSessionVideo>>
>;
export type SessionControllerGetSessionVideoQueryError = ErrorType<void>;

export function useSessionControllerGetSessionVideo<
  TData = Awaited<ReturnType<typeof sessionControllerGetSessionVideo>>,
  TError = ErrorType<void>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof sessionControllerGetSessionVideo>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sessionControllerGetSessionVideo>>,
          TError,
          Awaited<ReturnType<typeof sessionControllerGetSessionVideo>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSessionControllerGetSessionVideo<
  TData = Awaited<ReturnType<typeof sessionControllerGetSessionVideo>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof sessionControllerGetSessionVideo>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sessionControllerGetSessionVideo>>,
          TError,
          Awaited<ReturnType<typeof sessionControllerGetSessionVideo>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSessionControllerGetSessionVideo<
  TData = Awaited<ReturnType<typeof sessionControllerGetSessionVideo>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof sessionControllerGetSessionVideo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useSessionControllerGetSessionVideo<
  TData = Awaited<ReturnType<typeof sessionControllerGetSessionVideo>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof sessionControllerGetSessionVideo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSessionControllerGetSessionVideoQueryOptions(
    id,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
