/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Hackathon DH API
 * WIP
 * OpenAPI spec version: 1.0
 */
import type { DisfluencyToken } from './disfluencyToken';

export interface Disfluency {
  FP: DisfluencyToken[];
  RP: DisfluencyToken[];
  RV: DisfluencyToken[];
  RS: DisfluencyToken[];
  PW: DisfluencyToken[];
}
