/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Hackathon DH API
 * WIP
 * OpenAPI spec version: 1.0
 */
import type { Disfluency } from './disfluency';
import type { Transcription } from './transcription';

export interface FillerDto {
  disfluency: Disfluency;
  transcription: Transcription[];
  wpm: number[];
}
