/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Hackathon DH API
 * WIP
 * OpenAPI spec version: 1.0
 */
import type { PoseFrameDto } from './poseFrameDto';

export interface PoseDataCollectionDto {
  /** Array of pose data frames */
  poses: PoseFrameDto[];
}
