/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Hackathon DH API
 * WIP
 * OpenAPI spec version: 1.0
 */
import type { SessionUploadState } from './sessionUploadState';
import type { Users } from './users';
import type { PoseFrameDto } from './poseFrameDto';

export interface Session {
  id: number;
  name: string;
  description: string;
  createdAt: string;
  /** @nullable */
  videoFileName: string | null;
  /** @nullable */
  videoSize: number | null;
  /** @nullable */
  durationMs: number | null;
  uploadState: SessionUploadState;
  user: Users;
  userId: number;
  poseData: PoseFrameDto[];
}
