/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Hackathon DH API
 * WIP
 * OpenAPI spec version: 1.0
 */
import type { Users } from './users';

export interface Session {
  id: number;
  name: string;
  description: string;
  createdAt: string;
  videoFileName: string;
  durationMs: number;
  user: Users;
  userId: string;
}
