/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Hackathon DH API
 * WIP
 * OpenAPI spec version: 1.0
 */

export interface Transcription {
  text: string;
  start_ms: number;
  end_ms: number;
  confidence: number;
}
