/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Hackathon DH API
 * WIP
 * OpenAPI spec version: 1.0
 */
import type { TranscriptToken } from './transcriptToken';

export interface Transcript {
  id: string;
  text: string;
  tokens: TranscriptToken[];
}
