/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Hackathon DH API
 * WIP
 * OpenAPI spec version: 1.0
 */
import type { Session } from './session';

export interface Users {
  id: number;
  username: string;
  password: string;
  sessions: Session[];
}
